// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: bongs.sql

package database

import (
	"context"

	snowflake "github.com/disgoorg/snowflake/v2"
)

const addBong = `-- name: AddBong :exec
INSERT INTO bongs (guild_id, user_id, message_id, interaction_id, won, speed)
VALUES (?, ?, ?, ?, ?, ?)
`

type AddBongParams struct {
	GuildID       snowflake.ID `json:"guild_id"`
	UserID        snowflake.ID `json:"user_id"`
	MessageID     snowflake.ID `json:"message_id"`
	InteractionID snowflake.ID `json:"interaction_id"`
	Won           bool         `json:"won"`
	Speed         int64        `json:"speed"`
}

func (q *Queries) AddBong(ctx context.Context, arg AddBongParams) error {
	_, err := q.db.ExecContext(ctx, addBong,
		arg.GuildID,
		arg.UserID,
		arg.MessageID,
		arg.InteractionID,
		arg.Won,
		arg.Speed,
	)
	return err
}

const replaceUser = `-- name: ReplaceUser :exec
REPLACE INTO users (id, tag)
VALUES (?, ?)
`

type ReplaceUserParams struct {
	ID  snowflake.ID `json:"id"`
	Tag string       `json:"tag"`
}

func (q *Queries) ReplaceUser(ctx context.Context, arg ReplaceUserParams) error {
	_, err := q.db.ExecContext(ctx, replaceUser, arg.ID, arg.Tag)
	return err
}
