// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user-stats.sql

package database

import (
	"context"

	snowflake "github.com/disgoorg/snowflake/v2"
)

const userStats = `-- name: UserStats :one
SELECT count(speed) as total_bongs, cast(avg(speed) as float) as average_speed
FROM bongs
WHERE guild_id = ?
  and user_id = ?
  and won = true
LIMIT 1
`

type UserStatsParams struct {
	GuildID snowflake.ID `json:"guild_id"`
	UserID  snowflake.ID `json:"user_id"`
}

type UserStatsRow struct {
	TotalBongs   int64   `json:"total_bongs"`
	AverageSpeed float64 `json:"average_speed"`
}

func (q *Queries) UserStats(ctx context.Context, arg UserStatsParams) (UserStatsRow, error) {
	row := q.db.QueryRowContext(ctx, userStats, arg.GuildID, arg.UserID)
	var i UserStatsRow
	err := row.Scan(&i.TotalBongs, &i.AverageSpeed)
	return i, err
}
